# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: set up db
          command: >
            docker-compose run --rm
            -e RAILS_ENV=test
            -e AWS_ACCESS_KEY_ID
            -e AWS_SECRET_ACCESS_KEY
            -e AWS_PLATFORM_APPLICATION_APNS
            -e ES_HOST
            -e REDIS_HOST
            api bundle exec rake db:create db:schema:load --trace
      - run:
          name: lint
          command: >
            docker-compose run --rm
            api bundle exec rubocop
      - run:
          name: test
          command: >
            docker-compose run --rm
            -e RAILS_ENV=test
            -e AWS_ACCESS_KEY_ID
            -e AWS_SECRET_ACCESS_KEY
            -e AWS_PLATFORM_APPLICATION_APNS
            -e ES_HOST
            -e REDIS_HOST
            api bundle exec rspec
      - run:
          name: docker-compose down
          command: docker-compose down
